% file automatically generated by build_live_band
\version "2.24.0"
\include "../../styles/Global.ily"
\include "../../styles/final_styles/Instrument_Part_Score.ily"

\include "../../sources/overture.ly"
\include "../../sources/prelude.ly"
\include "../../sources/dancing_queen.ly"
\include "../../sources/waterloo.ly"

\pointAndClickOff

\book {
  \header {
    tagline = ##f
    part = "Rhythm Guitar"
  }

  \bookpart {
    \paper {
      print-page-number = ##f
    }

    \markup {
      \center-column {
        \vspace #10

        \fill-line {
          \huge \larger \larger
          \fontsize #4 \bold
          \center-column {
            "Thank You For The Music"
          }
        }

        \vspace #2

        \fill-line \huge \larger \larger {
          "TYFTM Music Division"
        }

        \vspace #2

        \fill-line \huge \larger \larger {
          "Rhythm Guitar Part Score, Live Band"
        }
      }
    }
  }

  \bookpart { \blank_page }
  \bookpart { \markuplist \table-of-contents }
  \bookpart { \blank_page }

  \bookpart {
    \tocItem i.ov \markup { "1. Overture" }

    \header {
      \overture_header
    }
    \score {
      \keepWithTag #'(r_guit nonchor) \overture

      \layout {}
    }
  }

  \bookpart {
    \tocItem i.prel \markup { "2. Prelude" }

    \header {
      \prelude_header
    }
    \markup {
      \vspace #14

      \fill-line {
        "Tacet"
      }
    }
  }

  \bookpart {
    \tocItem i.dq \markup { "8. Dancing Queen" }

    \header {
      \dancing_queen_header
    }
    \score {
      \keepWithTag #'(r_guit nonchor) \dancing_queen

      \layout {}
    }
  }

  \bookpart {
    \tocItem ii.wtl \markup { "27. Waterloo" }

    \header {
      \waterloo_header
    }
    \score {
      \keepWithTag #'(r_guit nonchor) \waterloo

      \layout {}
    }
  }

}