% file automatically generated by build_live_band
\version "2.24.0"
\include "../styles/global.ily"
\include "../styles/final_styles/Instrument_Part_Score.ily"

\include "../sources/overture.ly"
\include "../sources/prelude.ly"
\include "../sources/honey_honey.ly"
\include "../sources/our_last_summer.ly"
\include "../sources/mamma_mia.ly"
\include "../sources/chiquitita.ly"
\include "../sources/dancing_queen.ly"
\include "../sources/lay_all_your_love.ly"
\include "../sources/super_trouper.ly"
\include "../sources/gimme_gimme_gimme.ly"
\include "../sources/voulez_vous.ly"
\include "../sources/under_attack.ly"
\include "../sources/does_your_mother_know.ly"
\include "../sources/knowing_me.ly"
\include "../sources/slipping_through_my_fingers.ly"
\include "../sources/take_a_chance.ly"
\include "../sources/thank_you_for_the_music.ly"
\include "../sources/waterloo.ly"

\pointAndClickOff

\book {
  \header {
    tagline = ##f
    part = "Electric Keyboard"
  }

  \bookpart {
    \paper {
      print-page-number = ##f
    }

    \markup {
      \center-column {
        \vspace #10

        \fill-line {
          \huge \larger \larger
          \fontsize #4 \bold
          \center-column {
            "Thank You For The Music"
          }
        }

        \vspace #2

        \fill-line \huge \larger \larger {
          "TYFTM Music Division"
        }

        \vspace #2

        \fill-line \huge \larger \larger {
          "Electric Keyboard Part Score"
        }
      }
    }
  }

  \bookpart { \blank_page }
  \bookpart { \markuplist \table-of-contents }
  \bookpart { \blank_page }

  \bookpart {
    \tocSection i "Act I" 
    \tocItem i.ov \markup { "1. Overture" }

    \header {
      \overture_header
    }
    \score {
      \keepWithTag #'(e_kbd nonchor) \overture

      \layout {}
    }
  }

  \bookpart {
    \tocItem i.pr \markup { "2. Prelude" }

    \header {
      \prelude_header
    }
    \score {
      \keepWithTag #'(e_kbd nonchor) \prelude

      \layout {}
    }
  }

  \bookpart {
    \tocItem i.hh \markup { "3. Honey Honey" }

    \header {
      \honey_honey_header
    }
    \markup {
      \vspace #14

      \fill-line {
        "Tacet"
      }
    }
  }

  \bookpart {
    \tocItem i.ols \markup { "5. Our Last Summer" }

    \header {
      \our_last_summer_header
    }
    \markup {
      \vspace #14

      \fill-line {
        "Tacet"
      }
    }
  }

  \bookpart {
    \tocItem i.mm \markup { "6. Mamma Mia" }

    \header {
      \mamma_mia_header
    }
    \score {
      \keepWithTag #'(e_kbd nonchor) \mamma_mia

      \layout {}
    }
  }

  \bookpart {
    \tocItem i.chiq \markup { "7. Chiquitita" }

    \header {
      \chiquitita_header
    }
    \score {
      \keepWithTag #'(e_kbd nonchor) \chiquitita

      \layout {}
    }
  }

  \bookpart {
    \tocItem i.dq \markup { "8. Dancing Queen" }

    \header {
      \dancing_queen_header
    }
    \score {
      \keepWithTag #'(e_kbd nonchor) \dancing_queen

      \layout {}
    }
  }

  \bookpart {
    \tocItem i.layl \markup { "9. Lay All Your Love" }

    \header {
      \layl_header
    }
    \score {
      \keepWithTag #'(e_kbd nonchor) \layl

      \layout {}
    }
  }

  \bookpart {
    \tocItem i.st \markup { "10. Super Trouper" }

    \header {
      \super_trouper_header
    }
    \score {
      \keepWithTag #'(e_kbd nonchor) \super_trouper

      \layout {}
    }
  }

  \bookpart {
    \tocItem i.ggg \markup { "11. Gimme Gimme Gimme" }

    \header {
      \gimme_iiix_header
    }
    \score {
      \keepWithTag #'(e_kbd nonchor) \gimme_iiix

      \layout {}
    }
  }

  \bookpart {
    \tocItem i.vv \markup { "12. Voulez Vous" }

    \header {
      \voulez_vous_header
    }
    \score {
      \keepWithTag #'(e_kbd nonchor) \voulez_vous

      \layout {}
    }
  }

  \bookpart {
    \tocSection ii "Act II" 
    \tocItem ii.ua \markup { "14. Under Attack" }

    \header {
      \ua_header
    }
    \score {
      \keepWithTag #'(e_kbd nonchor) \under_attack

      \layout {}
    }
  }

  \bookpart {
    \tocItem ii.dymk \markup { "16. Does Your Mother Know" }

    \header {
      \dymk_header
    }
    \score {
      \keepWithTag #'(e_kbd nonchor) \dymk

      \layout {}
    }
  }

  \bookpart {
    \tocItem ii.kmky \markup { "17. Knowing Me, Knowing You" }

    \header {
      \knowing_me_header
    }
    \score {
      \keepWithTag #'(e_kbd nonchor) \knowing_me

      \layout {}
    }
  }

  \bookpart {
    \tocItem ii.sl \markup { "18. Slipping Through My Fingers" }

    \header {
      \slipping_header
    }
    \score {
      \keepWithTag #'(e_kbd nonchor) \slipping

      \layout {}
    }
  }

  \bookpart {
    \tocItem ii.tcm \markup { "22. Take a Chance on Me" }

    \header {
      \tcm_header
    }
    \score {
      \keepWithTag #'(e_kbd nonchor) \tcm

      \layout {}
    }
  }

  \bookpart {
    \tocItem ii.tyftm \markup { "24. Thank You For The Music" }

    \header {
      \tyftm_header
    }
    \markup {
      \vspace #14

      \fill-line {
        "Tacet"
      }
    }
  }

  \bookpart {
    \tocItem ii.wtl \markup { "27. Waterloo" }

    \header {
      \waterloo_header
    }
    \score {
      \keepWithTag #'(e_kbd nonchor) \waterloo

      \layout {}
    }
  }

}